### DISCUSSION TITLE
Docker compose deployment

### DISCUSSION THREAD

**Discussion by mgrimace** [thearyadev/MSRF#28] [Ideas]
Hello,

This is great and I was able to get it installed via Docker on my homelab server following the instructions. My suggestion is that typically I deploy new docker projects with a single docker compose file, compose.yaml, e.g., /opt/appdata/MSRF/compose.yaml, and I created a quick sample below. This would be great if at all possible for easy updates and docker deployment/redeployment, though I'm admittedly not sure what's involved in hosting an image like this somewhere. Purely a suggestion/idea if at all possible. Thanks for your work!

```
version: '3.9'
services:
  msrf:
    container_name: msrf
    image: [would need an image to point to vs., self-built, e.g. thearyadev/MSRF:latest)
    environment:
        - PUID=1000 #change this to your user's PID
        - PGID=1000 #change this to your user's PGID
        - TZ=America/Toronto
    ports:
        - 50947:50947  #webui port 
    volumes:
        - /opt/appdata/msrf/accounts:/msrf/accounts #directory which should contain the accounts.sqlite file
    restart: unless-stopped
```
